readme.txt

c65aedcf379f2b184eb52dc7fac0fa1b22f4a2b6 added `wp_slash()` which is not available before WordPress 3.6.

Bump Requires at least value to 3.6.

---

wordpress-importer.php

Backslashes are removed from comments on import. Not sure if this is the right place to add wp_slash?
See https://core.trac.wordpress.org/ticket/21007#comment:10

Add wp_slash before importing comment

---

wordpress-importer.php

Issue #16 - Remove the usage of screen_icon() which has been long deprecated.

Removing deprecated screen_icon().

---

phpunit/data/slashes.xml
phpunit/tests/import.php

Add Comment slashing unit test from https://core.trac.wordpress.org/attachment/ticket/21007/21007.2.diff
The fix was added in https://github.com/WordPress/wordpress-importer/commit/53a7def30e2376608d903af71e60ffc636cfbc1c but there existed no unit test for it.
Thanks to @ocean90

Add a unit test checking comment slashing

---

.travis.yml
src/readme.txt

* Don't use `sudo`. This is [no longer supported on Travis](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).
* Cache the correct directories for Composer.
* Add testing against PHP 7.3 and PHP 7.4 (dev).
* Simplify the Xdebug removal command.
* Fix the test matrix.
WP `trunk/latest` no longer support PHP < 5.6.20.
The plugin claims to support WP 3.6 and higher, however this can no longer be tested as due to a change in the unit test setup of WP Core in WP 3.7, the unit tests can not be run in combination with WP 3.6 anymore.
So for the highest stable PHP version, add a build against the lowest testable WP version, 3.7 and update the minimum WP requirement to WP 3.7.
For the lowest supported PHP version, `5.2`, a build against WP 3.7 fails with warnings about …

Update Travis script & minimum WP requirement

---

src/wordpress-importer.php

The [`wp_insert_category()`](https://developer.wordpress.org/reference/functions/wp_insert_category/) function returns the integer ID number of the new or updated Category on success or Zero or a `WP_Error` on failure.
While the code checks the return value of `wp_insert_category()` for `WP_Error`, it doesn't ask for a `WP_Error` by passing the second parameter `$wp_error` to `wp_insert_category()`.
This means that even when the insert/update failed and `wp_insert_category()` returns `0`, the code will still try to process the terms as well as the termmeta.
This bug has existed in the code from before this plugin was available on GitHub.
When processing the termmeta, `$id['term_id']` is passed as the second argument.
However, as stated above, `wp_insert_category()` - when successful - …

Bug fix: term meta data not importing

---

src/parsers.php

I added the `base_blog_url` variable,
This is needed to fix importing multiple files bug in WP-CLI https://github.com/wp-cli/import-command/pull/27
The problem is that WP-importer files from WPMU have the same base url for every blog, to recognise their  url the `base_blog_url` is needed. Having this we will able to group the processed post IDs correctly.

Added base_blog_url field

---

src/wordpress-importer.php

* Strip query arguments from file name.
* Fallback to md5 hash of URL for missing file name.
* Allow to override file name via Content-Disposition header.
* Use a mime type to file extension map for files without extension.
For testing I have used `https://avatars1.githubusercontent.com/u/617637?s=88&v=4` (=> `617637.png)` and `https://wordpress.org/latest.zip` (=> `wordpress-5.2.3.zip`).
See #24.

Improve imports of remote files without name and/or extensions.

---

src/class-wp-import.php

Ensures files are not compressed which may break the file size check after download.
Fixes #47.

Set Accept-Encoding header to identity for download.

---

src/parsers/class-wxr-parser-simplexml.php

As per the PHP 8.0 changelog:
> `libxml_disable_entity_loader()` has been deprecated. As libxml 2.9.0 is now
> required, external entity loading is guaranteed to be disabled by default,
> and this function is no longer needed to protect against XXE attacks.
Source: https://github.com/php/php-src/blob/71bfa5344ab207072f4cd25745d7023096338385/UPGRADING#L808-L811
Calling the function conditionally will prevent deprecation warnings.
And while the `PHP_VERSION_ID` constant was introduced in PHP 5.2.7, no additional condition is needed to check for its existance as the condition won't be executed when the `libxml_disable_entity_loader()` function exists check fails and as `libxml_disable_entity_loader()` was introduced in PHP 5.2.11, this means, we're good.

PHP 8.0: only call libxml_disable_entity_loader() in PHP < 8

---

phpcs.xml.dist

* Annotate the schema.
* Make the output more useful by showing progress and the error codes.
* Clean up the output by not showing the full path to files.
* Use parallel running of PHPCS whenever possible.
* Group the `testVersion` config with the `PHPCompatibilityWP` ruleset with which it belongs.

PHPCS: tweak the config

---

.github/workflows/test.yml
phpcs.xml.dist
phpunit/tests/term-meta.php
src/class-wp-import.php
src/compat.php
src/readme.txt
src/wordpress-importer.php

Includes:
* Adding `Requires PHP` headers.
* Updating the `Requires at least` (WP) headers.
* Stop detection of PHP compatibility issues for PHP < 5.6.
* CI: Stop testing on WP < 5.2 and PHP < 5.6.
Note: the PHP 7.4 and 8.0 builds against WP 5.2 were running into trouble due to WP itself not being fully compatible, so the CI matrix has been adjusted to only test against those PHP versions on WP versions which claim to be compatible with those PHP versions.
Includes tidying up the file docblock in the `wordpress-importer.php` file.
Closes #95
With WP 5.2 being the new minimum supported WP version, the polyfill for the `map_deep()` function is no longer needed.
Similarly, the bowing out for the term meta import (on WP < 4.4) is also no longer needed.

Raise minimum required WP version to WP 5.2 ( and PHP 5.6)

---

phpunit/tests/import.php
src/class-wp-import.php

Fixes PHP 8.1 `basename(): Passing null to parameter #1 ($path) of type string is deprecated` error due to the call to `parse_url()` returning `null` when the component requested does not exist in the passed URL, which in this case means a domain without trailing slash.
Includes a new unit test which would error out without this fix.
Note: the new test does not actually test the functioning of the `WP_Import::fetch_remote_file()` method in any significant way. It is only a regression test to prevent this particular PHP 8.1 deprecation notice from being reintroduced.

PHP 8.1: fix a "passing null to non-nullable" deprecation

---

.github/workflows/cs.yml

As per the [code sample in the CS2PR docs](https://github.com/staabm/annotate-pull-request-from-checkstyle#using-php_codesniffer), this minor change allows for displaying both the full report in the actual workflow, as well as displaying inline annotations on PRs.

GH Actions: minor tweak to CS workflow

---

src/class-wp-import.php

Setting the second param to true so that it always returns a `WP_Error` as opposed to `0`.
Fixes #122

Fix wp_insert_category fatal error

---

src/parsers/class-wxr-parser-regex.php
src/parsers/class-wxr-parser-xml.php

Dynamic (non-explicitly declared) property usage is expected to be deprecated as of PHP 8.2 and are expected to become a fatal error in PHP 9.0.
There are a number of ways to mitigate this:
* If it's an accidental typo for a declared property: fix the typo.
* For known properties: declare them on the class.
* For unknown properties: add the magic `__get()`, `__set()` et al methods to the class or let the class extend `stdClass` which has highly optimized versions of these magic methods build in.
* For unknown _use of_ dynamic properties, the `#[AllowDynamicProperties]` attribute can be added to the class. The attribute will automatically be inherited by child classes.
Refs:
* https://wiki.php.net/rfc/deprecate_dynamic_properties
In this case, the `parse()` method explicitly sets each of …

PHP 8.2 | Explicitly declare all properties

---

.github/workflows/test.yml

Now PR #128 has been merged, let's enable a GH Actions build against PHP 8.2.
While the build - for now - won't pass due to a PHP 8.1 issue with WP Core, I have done a test run which [didn't convert deprecations to exceptions](https://github.com/WordPress/wordpress-importer/runs/7320373532?check_suite_focus=true), and that run shows that the tests for the plugin itself will now pass.
Note: there are still plenty of deprecations coming from WP Core itself. Those are outside the scope of this ticket and not solvable here anyway.
The following WP Core tickets are open to address those:
* https://core.trac.wordpress.org/ticket/56033
* https://core.trac.wordpress.org/ticket/56034
~~Also note there is currently an issue with the GD extension on PHP 8.2. This - again - is outside the scope of …

GH Actions: add build against PHP 8.2

---

src/readme.txt
src/wordpress-importer.php

It's been a year since the last release, and there's been some changes: https://github.com/WordPress/wordpress-importer/compare/0.7...master
As noted with #126, we should bump the tested-up-to, but might as well release these changes too.

Prepare a 0.8 release

---

.github/workflows/test.yml

1. Now Ubuntu 20 is the current image, `mysqli` is available by default, including on PHP 5.6 and 7.0, so no need to require this specifically.
2. Setup-PHP uses the production `php.ini` by default, which means that the error reporting related settings are not optimal for test runs, Fixed by explicitly setting the ini values for select config settings.

GH Actions: tweak setup-php

---

src/readme.txt
src/wordpress-importer.php
wordpress-importer.php

This PR adds support for WordPress 6.2 and upgrades the plugin to 0.9.
- Tested with WordPress 6.2
- Tested with PHP 5.6, PHP 7.4.33, PHP 8.0
How to test:
- Clone the plugin under your working directory
- Using `wp-env` to test, if you haven't installed it, please visit [wp-env](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/#quick-tldr-instructions) for instructions
- It'll be easier if you have a `.wp-env.json` file at the root folder. For example, if your root folder is `oss-importer` and you can clone the plugin under this folder. Create `.wp.-env.json` file, you can change PHP version to the one you want to test with.
```
{
"phpVersion": "5.6",
"plugins": ["./wordpress-importer"]
}
``` 
- Run `wp-env start` to spin up the WordPress
- Navigate to …

Add support for WordPress 6.2

---

.github/workflows/asset-readme.yml

This PR fixes the error assets workflow by applying the develop version of `10up/action-wordpress-plugin-asset-update@develop`.

Fix error workflow actions for assets

---

src/readme.txt
src/wordpress-importer.php
wordpress-importer.php

Based on the suggestion [here](https://github.com/WordPress/wordpress-importer/pull/146#issuecomment-1500251181) it'll be better for us to use version 0.8.1 instead of 0.9

Update version to 0.8.1

---

.github/workflows/test.yml
src/readme.txt

- This PR test for WordPress 6.4.2 with PHP 7.0, 7.4 and 8.0.
- Since latest WordPress is not supporting PHP 5.6 anymore, we also need to modify `test.yml`
How to test:
- Clone the plugin under your working directory
- Using `wp-env` to test, if you haven't installed it, please visit [wp-env](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/#quick-tldr-instructions) for instructions
- It'll be easier if you have a `.wp-env.json` file at the root folder. For example, if your root folder is `oss-importer` and you can clone the plugin under this folder. Create `.wp.-env.json` file, you can change PHP version to the one you want to test with.
```
{
"phpVersion": "7.0",
"plugins": ["./wordpress-importer"]
}
``` 
- Run `wp-env start` to spin up the WordPress
- …

Update tested up to label and test matrix

---

.github/workflows/cs.yml
.github/workflows/test.yml

This removes the `paths-ignore` configuration.
While running the builds on commits which only have changes to the `md` or `txt` files has no actual benefit, as those files do not influence the build results, not running the builds prevents merging PRs as branch protection with required build statuses has been turned on.
This fixes that conundrum.

GH Actions: adjust the workflow triggers

---

.github/workflows/test.yml

GitHub has deprecated the use of `set-output` (and `set-state`) in favour of new environment files.
This commit updates workflows to use the new methodology.
Refs:
* https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files

GH Actions: fix use of deprecated `set-output`

---

.github/workflows/cs.yml

If there is a ruleset error, the `cs2pr` action doesn't receive an `xml` report and exits with a `0` error code, even though the PHPCS run failed (though not on CS errors, but on a ruleset error).
This changes the GH Actions workflow to allow for that situation and still fail the build in that case.

GH Actions: harden the workflow against PHPCS ruleset errors

---

.github/workflows/cs.yml
.github/workflows/test.yml

Caches used in GH Actions do not get updated, they can only be replaced by a different cache with a different cache key.
Now the predefined Composer install action this repo is using already creates a pretty comprehensive cache key:
> `ramsey/composer-install` will auto-generate a cache key which is composed of
the following elements:
> * The OS image name, like `ubuntu-latest`.
> * The exact PHP version, like `8.1.11`.
> * The options passed via `composer-options`.
> * The dependency version setting as per `dependency-versions`.
> * The working directory as per `working-directory`.
> * A hash of the `composer.json` and/or `composer.lock` files.
This means that aside from other factors, the cache will always be busted when changes are made to the (committed) `composer.json` or the …

GH Actions: bust the cache semi-regularly

---

src/readme.txt
src/wordpress-importer.php
wordpress-importer.php

Bumping version up to include latest changes:
* Update compatibility tested-up-to to WordPress 6.4.2.
* Update doc URL references.
* Adjust workflow triggers.

Bump version up to 0.8.2

---

.github/workflows/test.yml

This commit:
* Adds a proper set of builds against PHP 8.1, 8.2 and PHP 8.3 against low/high WP versions supported for those PHP versions as those PHP versions have been released and should be supported.
* Removes the "experimental" builds against PHP 8.1 and 8.2 as those PHP versions have been released and should be supported.
* Moves the builds against PHP 5.6 from the "complementary" builds section to the "PHP version support" section.
* Moves some comments around to make it more straight forward to understand how this matrix should be read and updated.
I've verified that all (nearly) WP versions between the lowest and the highest supported version now have at least one build.

GH Actions: update the matrix for latest WP/PHP

---

src/class-wp-import.php

During the post import we check whether the post already exists using [post_exists](https://developer.wordpress.org/reference/functions/post_exists/).
The query currently utilises post title and date parameters, which will run through all the posts to try and find a match.
In cases where we have a large number of posts this query can time out and the import fail.
Passing the `post_type` to `post_exists` function allows us to use the `type_status_date` key, which significantly drops the number of rows examined and the overall query time in certain instances.
This change would also fix some edge case scenarios with posts across post types having the same title and date.
Issue link: https://github.com/WordPress/wordpress-importer/issues/162

Update call to post_exists to include post_type in the query

---

composer.json
phpcs.xml.dist
phpunit/bootstrap.php
phpunit/tests/base.php
phpunit/tests/comment-meta.php
phpunit/tests/import.php
phpunit/tests/parser.php
phpunit/tests/postmeta.php
phpunit/tests/term-meta.php
src/class-wp-import.php
src/parsers.php
src/parsers/class-wxr-parser-regex.php
src/parsers/class-wxr-parser-simplexml.php
src/parsers/class-wxr-parser-xml.php
src/parsers/class-wxr-parser.php
src/wordpress-importer.php
wordpress-importer.php

* No need for requiring the Composer PHPCS plugin anymore as it now comes automatically with WPCS and removing the requirement allows WPCS to manage the supported versions, preventing conflicts (and will update to the 1.0.0 version).
* Minor tweak for a replaced sniff as per the changes in WPCS 3.0.0.
* Exclude one error code which would conflict with the minimum PHP requirement of this plugin.
Refs:
* https://github.com/WordPress/WordPress-Coding-Standards/releases/tag/3.0.0
* https://github.com/WordPress/WordPress-Coding-Standards/wiki/Upgrade-Guide-to-WordPressCS-3.0.0-for-ruleset-maintainers
To prevent any BC-breaks, all methods without explicit visibility have now been explicitly declared as `public`.
Mind: the `set_up()` and `tear_down()` methods in the tests _should_ be …

Start using WordPressCS 3.1

---

src/readme.txt

This PR updates the `Tested up to` label to WordPress 6.7-beta2.
Tested with WordPress 6.6.2 and 6.7-beta2
Tested with PHP `7.0`, `7.4`, `8.0`, `8.2`, `8.3`
How to test:
1. Clone the plugin under your working directory
2. Using `wp-env` to test, if you haven't installed it, please visit [wp-env](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/#quick-tldr-instructions) for instructions
It'll be easier to have a `.wp-env.json` file in the root folder. For example, if your root folder is blogger-importer, you can clone the plugin under this folder. Create a `.wp-env.json` file; you can change the PHP version to the one you want to test with.
```json
{
"phpVersion": "7.4",
"plugins": ["./wordpress-importer"]
}
```
Run `wp-env start` to spin up the …

Test plugin for WordPress 6.6.2 and 6.7-beta2

---

src/parsers/class-wxr-parser-xml.php
src/readme.txt

The XML Parser extension still supports a quite dated mechanism for method based callbacks, where the object is first set via `xml_set_object()` and the callbacks are then set by passing only the name of the method to the relevant parameters on any of the `xml_set_*_handler()` functions.
```php
xml_set_object( $parser, $my_obj );
xml_set_character_data_handler( $parser, 'method_name_on_my_obj' );
```
Passing proper callables to the `xml_set_*_handler()` functions has been supported for the longest time and is cross-version compatible. So the above code is 100% equivalent to:
```php
xml_set_character_data_handler( $parser, [$my_obj, 'method_name_on_my_obj'] );
```
The mechanism of setting the callbacks with `xml_set_object()` has now been deprecated as of PHP 8.4, in favour of passing …

PHP 8.4 | Remove use of xml_set_object()

---

phpunit/install.sh

SVN has been deprecated and removed on the GitHub platform and is causing tests to fail. This switches the setup commands to use Git.

Remove SVN commands.

---

.github/workflows/props-bot.yml

This introduces the Props Bot GitHub Action workflow to allow WordPress-flavored "props" tracking.
For more information, see [the initial blog post](https://make.wordpress.org/core/2024/02/01/new-commit-message-requirements-in-git-hello-props-bot/).

Introduce Props Bot

---

.github/workflows/test.yml

PHP 8.4 has been released and WP 6.7 is beta-compatible.
Ref: https://www.php.net/releases/8.4/en.php

GH Actions: run the tests against PHP 8.4

---

e2e/fixtures/wxr-base-url-rewriting.xml
e2e/import-wxr.spec.js
src/php-toolkit/DataLiberation/BlockMarkup/class-blockmarkupprocessor.php
src/php-toolkit/DataLiberation/BlockMarkup/class-blockmarkupurlprocessor.php

Backports https://github.com/WordPress/php-toolkit/pull/188 and adds an e2e test to ensure that relative URLs in block attributes are correctly detected and migrated.

Rewrite relative URLs in block attributes

---

src/readme.txt
src/wordpress-importer.php
wordpress-importer.php

Let's release [URL rewriting in block attributes.](https://github.com/WordPress/wordpress-importer/pull/213)

Version bump to 0.9.2

---

phpunit/data/wxr-flat-attachment-different-site.xml
phpunit/data/wxr-flat-attachment-same-site.xml
phpunit/tests/base.php
phpunit/tests/import.php
src/class-wp-import.php
src/php-toolkit/DataLiberation/BlockMarkup/class-blockmarkupurlprocessor.php
src/php-toolkit/DataLiberation/URL/class-wpurl.php

Ensures the correct remapping of URLs referencing media files found in the imported posts when URL rewriting is enabled.
Solves https://github.com/WordPress/wordpress-importer/issues/217
When URL rewriting is enabled, posts such as this one:
```html
```
Are imported as:
```html
```
The media URL rewriting, however, tries to do a second pass over the imported content to replace the original media URL with the current site's media URL. Assuming we're importing from a `YYYY/MM/{filename}` uploads structure to a flat `{filename}` structure, that media rewriting step would try to replace
```
https://my-old-site.com/subpath/wp-content/uploads/2008/06/canola2.jpg
```
with 
```
https://my-new-site.com/wp-content/uploads/canola2.jpg
```
However, that initial URL no longer exists in the content as …

Rewrite attachment URLs to the new URL structure
